export const SEND_MESSAGE = 'SEND_MESSAGE'
export const SEND_TYPING = "SEND_TYPING"
export const SEND_REACTION = "SEND_REACTION"
export const USER_ONLINE = "USER_ONLINE"
export const USER_OFFLINE = "USER_OFFLINE"
export const JOIN_ROOM = "JOIN_ROOM"
export const SOCKET_NEW_CONNECT = "NEW_CONNECT"
export const SOCKET_DISCONNECT_WITH_YOU = "DISCONNECT_WITH_YOU"
